### ISSUE TITLE
$label = null

### ISSUE THREAD

**Issue by outflux3** [Hani79/Processwire_FieldType_Select_Drop_Down#1]
Seems that if you don't use a pair, the $label is null and then you have no labels in the dropdown.

i changed line 55 to this:
$label = $value;

and it works, not sure why or how setting the label to null works, i guess the select field is supposed to handle that, but it isn't doing it

**Comment by Hani79** [comment]
This has been fixed in a more robust manner. Sorry for the delayed response.
